---
site:
  title: Modern GitOps Stack
  start_page: ROOT::index.adoc

antora:
  extensions:
    - "@antora/lunr-extension"

urls:
  latest_version_segment: latest # Define each component's latest version as the latest in the URL
content:
  tags: v*
  branches: ~
  sources:
    # Main Repository
    - url: https://github.com/GersonRS/modern-gitops-stack.git
      start_path: docs
      branches: []
      tags:
        # Build all version tags
        - "v@({1..9})*({0..9}).+({0..9})*({0..9}).*"

        # Exclude versions without proper folder structure or with generation errors
        # - "!v{1..3}.{0..9}.{1..9}"
        - "!v1.0.1"

    # Modules Repositories
    - url: https://github.com/GersonRS/modern-gitops-stack-module-argocd.git
      start_path: docs
      branches: []
      tags:
        - "v@({2..9})*({0..9}).+({0..9}).*"
        # # Exclude versions without proper folder structure or with generation errors
        - "!v2.0.0"
    - url: https://github.com/GersonRS/modern-gitops-stack-module-cert-manager.git
      start_path: docs
      branches: []
      tags:
        - "v@({2..9})*({0..9}).+({0..9}).*"
        # # Exclude versions without proper folder structure or with generation errors
        - "!v1.0.0"
        # - "!v1.0.0-alpha.*"
        # - "!v{3..4}.{0..1}.{0..2}"
    - url: https://github.com/GersonRS/modern-gitops-stack-module-cluster-aks.git
      start_path: docs
      branches: []
      tags:
        - "v@({2..9})*({0..9}).+({0..9}).*"
        # # Exclude versions without proper folder structure or with generation errors
        - "!v1.0.0"
    - url: https://github.com/GersonRS/modern-gitops-stack-module-cluster-eks.git
      start_path: docs
      branches: []
      tags:
        - "v@({2..9})*({0..9}).+({0..9}).*"
        # # Exclude versions without proper folder structure or with generation errors
        - "!v1.0.0*"
    - url: https://github.com/GersonRS/modern-gitops-stack-module-cluster-kind.git
      start_path: docs
      branches: []
      tags:
        - "v@({2..9})*({0..9}).+({0..9}).*"
        # # Exclude versions without proper folder structure or with generation errors
        - "!v1.0.0*"
        - "!v1.1.0*"
        # - "!v{1..2}.{0..1}.{0..1}"
    - url: https://github.com/GersonRS/modern-gitops-stack-module-keycloak.git
      start_path: docs
      branches: []
      tags:
        - "v@({2..9})*({0..9}).+({0..9}).*"
        # # Exclude versions without proper folder structure or with generation errors
        - "!v1.0.0"
    - url: https://github.com/GersonRS/modern-gitops-stack-module-kube-prometheus-stack.git
      start_path: docs
      branches: []
      tags:
        - "v@({2..9})*({0..9}).+({0..9}).*"
        # # Exclude versions without proper folder structure or with generation errors
        - "!v1.0.0"
        - "!v1.1.0"
    - url: https://github.com/GersonRS/modern-gitops-stack-module-loki-stack.git
      start_path: docs
      branches: []
      tags:
        - "v@({2..9})*({0..9}).+({0..9}).*"
        # # Exclude versions without proper folder structure or with generation errors
        - "!v1.0.0"
    - url: https://github.com/GersonRS/modern-gitops-stack-module-metallb.git
      start_path: docs
      branches: []
      tags:
        - "v@({2..9})*({0..9}).+({0..9}).*"
        # # Exclude versions without proper folder structure or with generation errors
        - "!v1.0.0"
        # - "!v1.0.0-alpha.*"
    - url: https://github.com/GersonRS/modern-gitops-stack-module-metrics-server.git
      start_path: docs
      branches: []
      tags:
        - "v@({2..9})*({0..9}).+({0..9}).*"
        # # Exclude versions without proper folder structure or with generation errors
        - "!v1.0.0"
    - url: https://github.com/GersonRS/modern-gitops-stack-module-minio.git
      start_path: docs
      branches: []
      tags:
        - "v@({2..9})*({0..9}).+({0..9}).*"
        # # Exclude versions without proper folder structure or with generation errors
        # - "!v1.0.0-alpha.*"
        - "!v1.0.0"
        # - "!v1.1.1"
    - url: https://github.com/GersonRS/modern-gitops-stack-module-thanos.git
      start_path: docs
      branches: []
      tags:
        - "v@({2..9})*({0..9}).+({0..9}).*"
        # # Exclude versions without proper folder structure or with generation errors
        # - "!v1.0.0-alpha.*"
    - url: https://github.com/GersonRS/modern-gitops-stack-module-traefik.git
      start_path: docs
      branches: []
      tags:
        - "v@({2..9})*({0..9}).+({0..9}).*"
        # # Exclude versions without proper folder structure or with generation errors
        - "!v1.0.0"
        - "!v1.1.0"
        - "!v1.2.0"
    - url: https://github.com/GersonRS/modern-gitops-stack-module-oidc-aws-cognito.git
      start_path: docs
      branches: []
      tags:
        - "v@({1..9})*({0..9}).+({0..9}).*"
        # Exclude versions without proper folder structure or with generation errors
        # - "!v1.0.0-alpha.*"
ui:
  bundle:
    url: https://github.com/GersonRS/modern-gitops-stack-antora-ui/releases/download/main-latest/ui-bundle.zip
    snapshot: true
