= Política de Segurança

Bem-vindo e obrigado por nos ajudar a criar soluções seguras para todos.

== Versões suportadas

[cols=",",options="header",]
|===
|Version |Supported
|0.x.x |:white_check_mark:
|===

== Relatando uma vulnerabilidade

Se você acredita ter encontrado uma vulnerabilidade de segurança em qualquer repositório de propriedade do *GersonRS*, informe-nos por meio de divulgação coordenada.

*Não relate vulnerabilidades de segurança por meio de problemas, discussões ou solicitações pull públicas do GitHub.*

Em vez disso, envie um email para security.inf@GersonRS.com.

Inclua o máximo possível das informações listadas abaixo para nos ajudar a entender e resolver melhor o problema:

* O tipo de problema (por exemplo, buffer overflow, injeção de SQL ou cross-site scripting)
* Caminhos completos dos arquivos de origem relacionados à manifestação do problema
* A localização do código-fonte afetado (tag/branch/commit ou URL direto)
* Qualquer configuração especial necessária para reproduzir o problema
* Instruções passo a passo para reproduzir o problema
* Prova de conceito ou código de exploração (se possível)
* Impacto do problema, incluindo como um invasor pode explorar o problema

Essas informações nos ajudarão a fazer a triagem do seu relatório mais rapidamente.

== Segurança

*GersonRS* leva a sério a segurança de nossos produtos e serviços de software, incluindo todos os repositórios de código-fonte aberto gerenciados por nossas organizações GitHub, como https://github.com/GersonRS[GersonRS].