= Diretrizes Gerais de Contribuição

// Esses URLs são usados no documento como estão para gerar novos URLs, portanto, não devem conter nenhuma barra final.
:url-main-repo: https://github.com/GersonRS/modern-gitops-stack

Este documento descreve as diretrizes gerais para contribuir com o Modern Gitops Stack.

O Modern Gitops Stack é uma coleção de módulos, cada um deles com seu próprio ciclo de lançamento, para facilitar o desenvolvimento e manutenção de cada módulo.

TIP: Um projeto GitHub publico está disponível https://github.com/users/GersonRS/projects/2[aqui]. É uma forma útil de acompanhar o andamento dos PRs e Issues de todos os repositórios. Para obter mais informações sobre como ele é implementado, verifique a página xref:ROOT:contributing/project_board.adoc[Project Board].

== Fluxo de trabalho de desenvolvimento

Quando um novo recurso ou correção é necessário, o fluxo de trabalho típico é o seguinte:

1. Você deve criar uma nova branch a partir da branch `main` do módulo que deseja trabalhar;
2. Trabalhe e teste em sua branch;
3. Quando você achar que sua feature/fix está pronto, crie um Pull Request para mesclar sua branch na branch `main`.

As subseções a seguir descrevem algumas das melhores práticas a serem seguidas ao trabalhar no Modern Gitops Stack.

=== Branches

* Mantenha o branch `main` limpa e apenas mescle Pull Requests nele.
* Crie uma nova branch para cada Pull Request. *O nome da branch deve ter um nome que condiz com a funcionalidade que deseja implementar, seguido de uma breve descrição do trabalho realizado na branch*, por exemplo `add-oidc-authentication`.

=== Commit messages

* Ao fazer commit na sua branch, você deve seguir a especificação https://www.conventionalcommits.org/[Conventional Commits]. *Isso também permitirá que a geração automatizada do changelog funcione corretamente.*

* Usamos os seguintes tipos de commit:

** *`feat`* - um novo recurso
** *`fix`* - uma correção de bug
** *`docs`* - apenas a documentação muda
** *`style`* - alterações que não afetam o significado do código (espaço em branco, formatação, falta de ponto e vírgula, etc)
** *`refactor`* - uma alteração de código que não corrige um bug nem adiciona um recurso
** *`ci`* - alterações nos arquivos e scripts de configuração do CI
** *`chore`* - outras alterações que realmente não modificam o código (pode ser um commit de mesclagem, por exemplo, `chore: rebase 'main' into 'ISMODERN-GITOPS-184-v1-docs' antes de mesclar PR `)

* *Se o seu commit adiciona uma alteração significativa, você deve adicionar um `!` após o tipo de commit*, por exemplo `feat!: add a breaking change`.
+
IMPORTANT: Adicionar uma alteração significativa acionará automaticamente um aumento na versão principal quando o módulo for lançado.

* O escopo do commit é opcional, mas recomendado:
** Pelo menos, para os módulos que possuem variantes, *recomenda-se incluir a variante no escopo (`eks`, `aks`, `gke` ou `kind`)*. Você pode simplesmente usar a variante ou até mesmo usar a variante como prefixo (por exemplo, `docs(eks-variables): add descriptions`).
** Se estiver modificando algo no gráfico, *você deve adicionar `chart` como escopo*.
** Caso contrário, os escopos recomendados poderiam ser apenas o tipo de código alterado, por exemplo, `variables`, `outputs`, `main`, etc.

* A especificação de commits convencional também permite adicionar um corpo e um rodapé à mensagem de commit. Você poderia usar o corpo para adicionar mais detalhes e contexto ao commit.

=== Pull Requests

* Você pode criar Pull Requests a partir da sua branch a qualquer momento durante o desenvolvimento, mas se ele não estiver pronto para ser mesclado, você deve marcá-lo como _Draft Pull Request_. Isso evitará que ele seja mesclado por engano, ao mesmo tempo que permitirá que você obtenha feedback de outros desenvolvedores, bem como verificações automatizadas e geração de documentação feitas pelo GitHub Actions.

* Para que um PR seja mesclado, você precisa ter pelo menos uma revisão de outro desenvolvedor e todas as verificações automatizadas devem ser aprovadas. Comentários sobre o PR são bem-vindos e nos permitem acompanhar as discussões que acontecem no PR.

* *Preferimos usar a opção `Rebase and Merge` ao mesclar um PR.* Isso permite que o processo de liberação automática adicione múltiplas entradas no changelog, uma para cada commit no PR. *Isto é particularmente útil quando o PR contém múltiplas alterações*, por exemplo, ao adicionar um novo recurso e corrigir um bug ao mesmo tempo.
+
IMPORTANT: A desvantagem desta abordagem é que o histórico de commits precisa ser cuidado. Por exemplo, ter vários commits que dizem `docs: fix typo` não é apropriado. *Neste caso, você deve compactar manualmente os commits em um único commit com uma mensagem de commit adequada.* O mesmo vale para vários commits que foram usados iterativamente para corrigir um bug ou desenvolver um recurso. *Nesse caso, você deve compactar os commits em um único commit, um para cada correção ou recurso.*

//TODO Talvez adicionar um exemplo de um histórico de commits bom e um histórico de commits ruim.

* Tome cuidado para intitular e descrever adequadamente seu pull requests. *O título deve ser suficientemente descritivo e seguir as especificações convencionais dos commits*. Quanto à descrição, siga o modelo fornecido.
+
IMPORTANT: Se você fizer um `Squash and Merge` em um Pull Request, *a mensagem de commit será o título do Pull Request*. Portanto, certifique-se de que o título seja descritivo o suficiente e siga a especificação convencional dos commits, caso contrário terei que corrigir manualmente a mensagem do commit na branch `main`, o que é no mínimo inconveniente.

=== Problemas

* Se você encontrar algum problema no Modern Gitops Stack, poderá criar uma issue no repositório em que o encontrou. Um problema pode ser um bug ou uma solicitação/proposta de feature.

* Se for um bug, descreva o problema adequadamente e forneça o máximo de contexto possível.

* Se for uma solicitação/proposta de feature, descreva por que a feature é necessário e qual problema ele resolverá para você.

* *As questões são mais úteis para usuários externos do Modern Gitops Stack*, se possível podemos discutir o assunto em uma reunião e então decidir se é algo que queremos implementar ou não. Nesse caso, podemos então criar um card no backlog, para acompanhar o trabalho que precisa ser feito.