= GitHub Project Board

// Esses URLs são usados no documento como estão para gerar novos URLs, portanto, não devem conter nenhuma barra final.
:url-main-repo: https://github.com/GersonRS/modern-gitops-stack

Para aliviar o fardo dos mantenedores do projeto, existe um Project Board no GitHub usado para acompanhar o progresso dos PRs e issues. O quadro está disponível para qualquer um e está disponível https://github.com/users/GersonRS/projects/2/[aqui]. Todos os repositórios do Modern Gitops Stack também estão conectados a este projeto no momento da criação.

A maneira como isso é feito é um tanto complicada, daí o motivo desta página de documentação.

== Projeto Modern Gitops Stack

O projeto em si foi criado manualmente na conta https://github.com/orgs/GersonRS/[`@GersonRS`], usando a interface web do GitHub (https://docs.github.com/en/issues/planning-and-tracking-with-projects/creating-projects/creating-a-project[documentação]). *O projeto esta publico (https://docs.github.com/en/issues/planning-and-tracking-with-projects/managing-your-project/managing-visibility-of-your-projects[documentação]) e acessível para qualquer um (`por enquanto`)* (https://docs.github.com/en/issues/planning-and-tracking-with-projects/managing-your-project/managing-access-to-your-projects[documentação]).

Todos os quadros e tabelas também foram criados manualmente. Nas configurações do projeto, existem fluxos de trabalho de automação (https://docs.github.com/en/issues/planning-and-tracking-with-projects/automating-your-project/using-the-built-in-automations[documentação]) que movimentam as issues e PRs dependendo de seu status (aberto, fechado, mesclado, etc.).

== Adicionando um PR/issue ao projeto

Como existem alguns limites de quantos repositórios podemos adicionar a um projeto usando os fluxos de trabalho padrão, fui forçado a automatizar esse processo usando um workflow do GitHub, conforme sugerido em https://docs.github.com/en/issues/planning-and-tracking-with-projects/automating-your-project/automating-projects-using-actions#example-workflow-authenticating-with-a-github-app[documentação oficial].

Embora a documentação oficial chame explicitamente a API com comandos `gh`, optei por usar uma ação oficial do GitHub (https://github.com/actions/add-to-project[`actions/add-to-project`]) para conseguir isso. Além disso, para permitir que os fluxos de trabalho modificassem o projeto, precisei criar um token GitHub cujo único propósito é fornecer as permissões necessárias aos workflows.

=== Fluxo de trabalho centralizado

A definição do fluxo de trabalho está disponível no {url-main-repo}/blob/main/.github/workflows/pr-issues-project.yaml[repositório principal].

[source,yaml]
----
include::examples$github_workflows/pr-issues-project.yaml[]
----