= Pilha de Gitops Moderna

:palavras-chave: terraform, kubernetes, kind, eks, aks, terraform, argocd, grafana, loki, traefik, prometheus, cert-manager, openid-connect, antora
:sectanchors:

// Essas URLs são usadas no documento como estão para gerar novas URLs, portanto, não devem conter nenhuma barra final.
:url-main-repo: https://github.com/GersonRS/modern-gitops-stack
:url-c2c: https://gersonrs.github.io
:url-devops-stack-repo: https://github.com/camptocamp/devops-stack

imagem::modern-gitops-stack-logo_large.png[Pilha moderna de Gitops]

O Modern Gitops Stack fornece uma plataforma Kubernetes de implantação padronizada, reunindo provisionamento automatizado como código, implantação contínua de aplicativos e configurações prontas para as melhores ferramentas nativas da nuvem do setor.

DICA: A maneira mais fácil de começar com o Modern Gitops Stack é seguir o tutorial na página xref:ROOT:tutorials/deploy_kind.adoc[Deployment on KinD]. Este tutorial deixará você com um playground https://kind.sigs.k8s.io/[KinD] totalmente operacional em sua máquina local.

== Projeto

Este projeto é uma extensão do projeto {url-devops-stack-repo}[DevOps Stack]. *É uma extensão focada em GitOps e MLOps para desenvolvimento e implantação de Modelos de Machine Learning*. Seu código-fonte é aberto e distribuído sob a licença Apache 2.

== Explicação rápida

O Modern Gitops Stack é composto por vários módulos Terraform usados para implantar um cluster Kubernetes junto com uma pilha de componentes que permitirá implantar aplicativos, bem como monitorar e solucionar problemas de seu cluster.

A escolha do módulo de cluster depende do provedor no qual você deseja implantar seu cluster. O Modern Gitops Stack atualmente oferece suporte ao Amazon EKS, Azure AKS e uma implantação de teste local usando KinD. Os módulos que implantam os componentes restantes da pilha são tão genéricos quanto possível, mas alguns possuem variantes específicas do provedor que implantam recursos diferentes dependendo da plataforma.

Como você verá nos exemplos, após a implantação do cluster, um CD Argo temporário é instalado para então implantar o restante dos componentes. Após a implantação de todos os componentes, esta instância do Argo CD é substituída por uma permanente que gerenciará as atualizações de todos os componentes e poderá ser usada para implantar suas aplicações (também criamos módulos para criar e configurar o Argo CD).

== Documentação

Estas páginas de documentação são a principal fonte de informações para o Modern Gitops Stack. Eles são escritos em https://asciidoc.org/[AsciiDoc] e construídos usando https://antora.org/[Antora].

A documentação principal contém informações relativas ao Modern Gitops Stack como um todo, enquanto as páginas do módulo contêm detalhes mais específicos e técnicos sobre cada módulo individual. Recomendamos que você dê uma olhada na documentação geral primeiro para ter uma visão geral de uma implantação do Modern Gitops Stack e depois navegue na barra lateral para consultar a documentação de cada módulo.

Esta documentação, bem como alguns exemplos, estão armazenados no {url-main-repo}[repositório principal no GitHub].

== Contribuindo

Na seção de contribuição da barra lateral você encontrará algumas orientações sobre como contribuir para o Modern Gitops Stack. Você tem algumas xref:ROOT:contributing/general_guidelines.adoc[diretrizes gerais] sobre como contribuir para o projeto junto com explicações sobre xref:ROOT:contributing/modules.adoc[como um módulo é estruturado], xref:ROOT:contributing/ documentação.adoc[como escrever documentação] e xref:ROOT:contributing/release.adoc[como funciona o processo de lançamento].

Aceitamos qualquer tipo de contribuição, seja um relatório de bug, uma solicitação de recurso, uma melhoria na documentação ou até mesmo uma contribuição de código. Você também pode criar seus próprios módulos de provisionamento de cluster e solicitar nossa ajuda, mas não podemos garantir qualquer manutenção ou suporte de longo prazo para eles.