apiVersion: v2
dependencies:
- name: thanos
  repository: https://charts.bitnami.com/bitnami
  version: 13.2.2
- name: redis
  repository: https://charts.bitnami.com/bitnami
  version: 18.17.0
name: thanos
version: "0"
