---
name: "linters"
run-name: Checking commits and code by @${{ github.actor }}
on:
  pull_request:

jobs:
  linters:
    uses: GersonRS/modern-gitops-stack/.github/workflows/modules-linters.yaml@main
