---
# GitHub Actions workflow to automatically push PRs and issues to the Modern Gitops Stack project board.
#
# IMPORTANT: This workflow is called by other workflows in our Modern Gitops Stack repositories and it is centralized here in
# order to be easily maintained across modules. Because of this, please make sure you're not introducing any breaking
# changes when modifying this workflow.

name: "pr-issues-project"

on:
  workflow_call:
    secrets:
      PROJECT_APP_PRIVATE_KEY:
        description: "GitHub App private key for the Modern Gitops Stack Project app"
        required: true

  issues:
    types:
      - opened
      - reopened

  pull_request:
    types:
      - opened
      - reopened

jobs:
  add-to-project:
    runs-on: ubuntu-latest
    steps:
      - name: Generate authentication token from GitHub App
        id: generate_token
        uses: actions/create-github-app-token@v1
        with:
          app-id: 882683
          private-key: ${{ secrets.PROJECT_APP_PRIVATE_KEY }}

      - name: Add PR or issue to Modern GitOps Stack project board
        uses: actions/add-to-project@v1.0.1
        with:
          project-url: https://github.com/users/GersonRS/projects/1
          github-token: ${{ steps.generate_token.outputs.token }}
          labeled: bug, needs-triage
          label-operator: NOT
