---
name: "publish-antora-docs"

on:
  push:
    branches:
      - main
    paths:
      - "version.txt" # Trigger a build when the version changes in order to take the version tag into account

  schedule:
    # Every day at 3:00 AM in order to generate documentation for every module that had a new release
    - cron: "0 3 * * *"

  pull_request:
    paths:
      - "docs/**"

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

concurrency:
  group: github-pages
  cancel-in-progress: false
# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Configure Pages
        uses: actions/configure-pages@v3
      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "18"
      - name: Install Antora with the Antora Lunr Extension
        run: npm i antora @antora/lunr-extension
      - name: Generate Site
        run: npx antora antora-playbook.yml
      - name: Upload Artifacts
        uses: actions/upload-pages-artifact@v2
        with:
          path: build/site
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v2
