---
name: "release-please"

on:
  push:
    branches:
      - main

jobs:
  release-please:
    runs-on: ubuntu-latest
    outputs:
      releases_created: ${{ steps.release-please.outputs.releases_created }}
    steps:
      - uses: google-github-actions/release-please-action@v4
        id: release-please
        with:
          release-type: simple
          config-file: .release-please-config.json
          manifest-file: .release-please-manifest.json
