---
name: "release-please"

on:
  push:
    branches:
      - main

jobs:
  release:
    uses: GersonRS/modern-gitops-stack/.github/workflows/modules-release-please.yaml@main
    secrets:
      PAT: ${{ secrets.PAT }}
